Document: collectd
Title: Debian collectd Manual
Author: <insert document author here>
Abstract: This manual describes what collectd is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/collectd/collectd.sgml.gz

Format: postscript
Files: /usr/share/doc/collectd/collectd.ps.gz

Format: text
Files: /usr/share/doc/collectd/collectd.text.gz

Format: HTML
Index: /usr/share/doc/collectd/html/index.html
Files: /usr/share/doc/collectd/html/*.html
